adding mdx support

diff --git a/Dockerfile.dev b/Dockerfile.dev
--- a/Dockerfile.dev
+++ b/Dockerfile.dev
@@ -1,55 +1,73 @@
-# Use the node:22-alpine image as the base
-FROM node:22-alpine3.20 AS base
+FROM node:20-alpine3.20 AS base
 
-# Install libc6-compat which might be needed according to Node.js Docker best practices
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
-
-# Set the working directory in the container
 WORKDIR /app
 
-# Copy package.json and package-lock.json
-COPY package.json package-lock.json* ./
-
-# Install all dependencies (including 'devDependencies' for development purposes)
-RUN npm install
-
-# For production, consider installing only production dependencies
-FROM base AS production-dependencies
-RUN npm ci --only=production
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # Rebuild the source code only when needed
 FROM base AS builder
 WORKDIR /app
-
-# Copy the application source code excluding node_modules
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-# Build the Next.js application
-RUN npm run build
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+ENV NEXT_TELEMETRY_DISABLED=1
 
-# Development image, copy all the files and prepare for running the app
-FROM base AS dev
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Production image, copy all the files and run next
+FROM base AS runner
 WORKDIR /app
 
-# Set environment variables
-# ENV NODE_ENV=development
-ENV PORT=3000
-ENV HOSTNAME="0.0.0.0"
+ENV NODE_ENV=production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+ENV NEXT_TELEMETRY_DISABLED=1
 
-# Create a non-root user and group
-RUN addgroup --system --gid 1001 nodejs && \
-	adduser --system --uid 1001 nextjs
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
-# Copy the build output to the dev stage, excluding node_modules as it will be mounted
 COPY --from=builder /app/public ./public
-COPY --from=builder /app/.next ./.next
 
-# Set the correct permissions for the Next.js application
-RUN chown -R nextjs:nodejs .next
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown -R nextjs:nodejs /app
+
+# Ensure node_modules directory is writable
+COPY --from=builder /app/node_modules ./node_modules
+RUN chown -R nextjs:nodejs ./node_modules
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
 USER nextjs
 
-# Expose the port the app runs on
 EXPOSE 3000
 
-# Start the Next.js application
-CMD ["node", "node_modules/next/dist/bin/next", "start"]
+ENV PORT=3000
+
+ENV HOSTNAME="0.0.0.0"
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+# CMD HOSTNAME="0.0.0.0" node server.js
+CMD ["node", "server.js"]
